In [3]:
import torch
print(torch.cuda.is_available())  # Should return True
print(torch.version.cuda)  # Should show a CUDA version
print(torch.cuda.device_count())  # Should show the number of GPUs
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU detected")

True
12.1
1
NVIDIA GeForce GTX 1650


### Basic Tensors

Note : Matrix and tensors are written in capitalcase

In [13]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

In [12]:
TENSOR[0][0][1]

tensor(2)

### Random Tensors

In [16]:
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.5714, 0.7485, 0.2213, 0.0659],
         [0.7428, 0.1091, 0.4646, 0.3952],
         [0.9216, 0.8460, 0.9733, 0.9634]],

        [[0.2336, 0.1411, 0.2225, 0.0082],
         [0.1395, 0.0637, 0.7089, 0.2049],
         [0.8187, 0.8375, 0.3824, 0.4999]]])

### Important Tensors parameters

In [18]:
float_32_tensors = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,
                                device=None,
                                requires_grad=False)

float_32_tensors

tensor([3., 6., 9.])

In [19]:
float_32_tensors.dtype

torch.float32

In [20]:
float_16_tensors = float_32_tensors.type(torch.float16)
float_16_tensors.dtype

torch.float16

In [26]:
r = torch.rand(3,2)
r2 = torch.rand(3, 2)
print(r)
print(r2)

tensor([[0.1830, 0.4980],
        [0.8766, 0.2420],
        [0.4320, 0.1927]])
tensor([[0.8928, 0.3930],
        [0.4104, 0.7980],
        [0.9069, 0.4105]])


In [ ]:
# will 
result = torch.matmul(r, r2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)