In [4]:
import torch
print(torch.cuda.is_available())  # Should return True
print(torch.version.cuda)  # Should show a CUDA version
print(torch.cuda.device_count())  # Should show the number of GPUs
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU detected")

False
None
0
No GPU detected


### Basic Tensors

Note : Matrix and tensors are written in capitalcase

In [5]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

In [6]:
TENSOR[0][0][1]

tensor(2)

### Random Tensors

In [7]:
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.0616, 0.0114, 0.7935, 0.3169],
         [0.9775, 0.8811, 0.3615, 0.6008],
         [0.4721, 0.5657, 0.9938, 0.7326]],

        [[0.1928, 0.9234, 0.7103, 0.0447],
         [0.7550, 0.4548, 0.2493, 0.3568],
         [0.1720, 0.9087, 0.3916, 0.3744]]])

### Important Tensors parameters

In [8]:
float_32_tensors = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,
                                device=None,
                                requires_grad=False)

float_32_tensors

tensor([3., 6., 9.])

In [9]:
float_32_tensors.dtype

torch.float32

In [10]:
float_16_tensors = float_32_tensors.type(torch.float16)
float_16_tensors.dtype

torch.float16

In [11]:
r = torch.rand(3,2)
r2 = torch.rand(3, 2)
print(r)
print(r2)

tensor([[0.6818, 0.7306],
        [0.3828, 0.7735],
        [0.2165, 0.8710]])
tensor([[0.8880, 0.5086],
        [0.9556, 0.5441],
        [0.1387, 0.3335]])


In [ ]:
# will return an error  because of inner dimension matrix multiplication mismatch!
result = torch.matmul(r, r2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [14]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [20]:
x_reshaped = x.reshape(3, 3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [26]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [52]:
x = torch.zeros(1, 1, 2)
x

tensor([[[0., 0.]]])

In [45]:
# squeeze method
y = torch.squeeze(x)
y

tensor([0., 0.])

In [67]:
z = torch.zeros(9)
z_unsqueezed = z.unsqueeze(dim=0)
z, z_unsqueezed

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.]]))

In [77]:
# torch permute methods
x = torch.randn(1, 9)
x_permuted = torch.permute(x, (1, 0))
print(x.size())
print(x_permuted.size())

torch.Size([1, 9])
torch.Size([9, 1])
