In [1]:
import torch
print(torch.cuda.is_available())  # Should return True
print(torch.version.cuda)  # Should show a CUDA version
print(torch.cuda.device_count())  # Should show the number of GPUs
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU detected")

True
12.1
1
NVIDIA GeForce GTX 1650


### Basic Tensors

Note : Matrix and tensors are written in capitalcase

In [2]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

In [3]:
TENSOR[0][0][1]

tensor(2)

### Random Tensors

In [4]:
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.4639, 0.6297, 0.4898, 0.3415],
         [0.5628, 0.2713, 0.6448, 0.0087],
         [0.4477, 0.0579, 0.8176, 0.8692]],

        [[0.2508, 0.7173, 0.5505, 0.1129],
         [0.5071, 0.2997, 0.2691, 0.5278],
         [0.9576, 0.4726, 0.2443, 0.0939]]])

### Important Tensors parameters

In [5]:
float_32_tensors = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,
                                device=None,
                                requires_grad=False)

float_32_tensors

tensor([3., 6., 9.])

In [6]:
float_32_tensors.dtype

torch.float32

In [7]:
float_16_tensors = float_32_tensors.type(torch.float16)
float_16_tensors.dtype

torch.float16

In [8]:
r = torch.rand(3,2)
r2 = torch.rand(3, 2)
print(r)
print(r2)

tensor([[0.1693, 0.6313],
        [0.8831, 0.0979],
        [0.8719, 0.3236]])
tensor([[0.6529, 0.6801],
        [0.1813, 0.9943],
        [0.4549, 0.0787]])


In [9]:
# will 
result = torch.matmul(r, r2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [13]:
# indexing
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
x[0][0][1]

tensor(2)

In [32]:
x[:5, 0:3]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [65]:
print(x[0][2][1])

tensor(8)


In [69]:
# Random seed

random_seed = 10

torch.manual_seed(random_seed)
random_1 = torch.rand(2, 4)

torch.manual_seed(random_seed)
random_2 = torch.rand(2, 4)

print(random_1)
print(random_2)
print(random_1 == random_2)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693]])
tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693]])
tensor([[True, True, True, True],
        [True, True, True, True]])


### Using GPUS instead of CPU For computing tensors

In [76]:
!nvidia-smi

Thu Mar 13 15:50:05 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.14                 Driver Version: 566.14         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:29:00.0  On |                  N/A |
| 43%   58C    P0             38W /   75W |    3822MiB /   4096MiB |    100%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [77]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [78]:
torch.cuda.device_count()

1

In [80]:
tensor = torch.tensor([[1, 2, 3]])


print(tensor, tensor.device)

tensor([[1, 2, 3]]) cpu


In [81]:
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([[1, 2, 3]], device='cuda:0')

#### Revert back to CPUs

In [82]:
tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [84]:
tensor_cpu = tensor_gpu.cpu().numpy()
tensor_cpu  

array([[1, 2, 3]], dtype=int64)

In [91]:
original_tensor = torch.from_numpy(tensor_cpu)
print(original_tensor.type(torch.float32).dtype)

torch.float32
